-- Generated CupMate news seed. Run in Supabase SQL Editor if anon inserts are blocked.

insert into public.articles (id, type, status, category, image_url, source_url, published_at) values ('0379fb64-9e65-4ecb-803d-52fd9481bd03', 'news', 'published', 'Teams', 'https://global.ariseplay.com/amg/www.thisdaylive.com/uploads/1-790.jpg', 'https://www.thisdaylive.com/2026/04/02/iraq-completes-48-team-line-up-for-2026-world-cup/', '2026-04-02T04:15:00+00:00') on conflict (id) do nothing;
insert into public.article_translations (article_id, language_code, slug, title, excerpt, body, seo_title, seo_description) values ('0379fb64-9e65-4ecb-803d-52fd9481bd03', 'en', 'iraq-completes-48-team-world-cup-lineup', 'Iraq completes the 48-team World Cup lineup', 'Iraq''s qualification closes the expanded 48-team field for the 2026 FIFA World Cup.', 'The expanded 2026 FIFA World Cup field is now complete after Iraq secured the final qualifying place. For fans, the confirmed lineup makes itinerary planning, team following and group-stage alerts much more useful inside CupMate.', 'Iraq completes the 48-team World Cup lineup', 'Iraq''s qualification closes the expanded 48-team field for the 2026 FIFA World Cup.') on conflict (article_id, language_code) do nothing;

insert into public.articles (id, type, status, category, image_url, source_url, published_at) values ('6081ab6b-9bc2-4b63-b913-92f270adc6e8', 'news', 'published', 'Culture', 'https://stat5.bollywoodhungama.in/wp-content/uploads/2026/05/Nora-Fatehi-FIFA-World-Cup-2026.jpeg', 'https://www.bollywoodhungama.com/news/bollywood/nora-fatehi-to-perform-and-sing-at-fifa-world-cup-2026-opening-ceremony-in-toronto/', '2026-05-09T08:30:00+00:00') on conflict (id) do nothing;
insert into public.article_translations (article_id, language_code, slug, title, excerpt, body, seo_title, seo_description) values ('6081ab6b-9bc2-4b63-b913-92f270adc6e8', 'en', 'nora-fatehi-world-cup-opening-ceremony-toronto', 'Nora Fatehi linked to World Cup opening ceremony in Toronto', 'Reports point to Nora Fatehi joining the entertainment lineup around the 2026 World Cup opening ceremony.', 'World Cup culture continues to build around Toronto, with entertainment reports linking Nora Fatehi to opening-ceremony activity. CupMate can use stories like this to enrich city guides, fan festival recommendations and pre-match planning.', 'Nora Fatehi linked to World Cup opening ceremony in Toronto', 'Reports point to Nora Fatehi joining the entertainment lineup around the 2026 World Cup opening ceremony.') on conflict (article_id, language_code) do nothing;

insert into public.articles (id, type, status, category, image_url, source_url, published_at) values ('4a09cba9-d102-4bcb-8c4d-ab2fb0d6dc31', 'news', 'published', 'Streaming', 'https://d.techtimes.com/en/full/463397/youtube-fifa-world-cup-2026.jpg', 'https://www.techtimes.com/articles/315227/20260318/fifa-selects-youtube-its-preferred-platform-world-cup-2026will-it-affect-streaming.htm', '2026-03-18T17:45:00+00:00') on conflict (id) do nothing;
insert into public.article_translations (article_id, language_code, slug, title, excerpt, body, seo_title, seo_description) values ('4a09cba9-d102-4bcb-8c4d-ab2fb0d6dc31', 'en', 'fifa-youtube-preferred-platform-world-cup-2026', 'FIFA selects YouTube as preferred platform for World Cup 2026 coverage', 'A streaming-platform partnership could shape how fans discover tournament clips and coverage.', 'FIFA''s platform strategy is becoming part of the World Cup viewing story. A preferred YouTube relationship could make official clips, highlights and fan-facing video content easier to discover before and during the tournament.', 'FIFA selects YouTube as preferred platform for World Cup 2026 coverage', 'A streaming-platform partnership could shape how fans discover tournament clips and coverage.') on conflict (article_id, language_code) do nothing;

insert into public.articles (id, type, status, category, image_url, source_url, published_at) values ('550cfedf-a808-4e6d-bd03-8d99a4c243d9', 'news', 'published', 'Travel', 'https://www.deccanchronicle.com/h-upload/2026/04/13/2030826-l-r-ravi-santhanam-ashish-parthasarthy-ahaan-pandey-michael-owen-danielle-jin-rishi-chhabra-rajanish-prabhu.jpg', 'https://www.deccanchronicle.com/business/in-other-news/visa-and-hdfc-bank-bring-indian-fans-closer-to-the-fifa-world-cup-2026-1950225', '2026-04-13T19:15:00+00:00') on conflict (id) do nothing;
insert into public.article_translations (article_id, language_code, slug, title, excerpt, body, seo_title, seo_description) values ('550cfedf-a808-4e6d-bd03-8d99a4c243d9', 'en', 'visa-hdfc-world-cup-fan-access-promotion', 'Visa and HDFC Bank launch World Cup fan access promotion', 'A new India-focused card promotion adds another route for fans planning World Cup travel.', 'Visa and HDFC Bank introduced a World Cup-linked promotion for Indian fans, showing how travel, payments and fan experiences are converging ahead of 2026. For CupMate users, these developments matter when planning cross-border trips and ticket-adjacent experiences.', 'Visa and HDFC Bank launch World Cup fan access promotion', 'A new India-focused card promotion adds another route for fans planning World Cup travel.') on conflict (article_id, language_code) do nothing;

insert into public.articles (id, type, status, category, image_url, source_url, published_at) values ('95f5c074-1e5d-4bc9-9cea-749878ade568', 'news', 'published', 'Commerce', null, 'https://www.businesswire.com/news/home/20260512823018/en/Lays-Introduces-Four-New-FIFA-World-Cup-2026-Inspired-Potato-Chip-Flavours-in-Canada', '2026-05-12T14:50:00+00:00') on conflict (id) do nothing;
insert into public.article_translations (article_id, language_code, slug, title, excerpt, body, seo_title, seo_description) values ('95f5c074-1e5d-4bc9-9cea-749878ade568', 'en', 'lays-world-cup-inspired-flavors-canada', 'Lay''s introduces World Cup-inspired flavors in Canada', 'Tournament marketing is accelerating in Canada with new FIFA World Cup themed snack flavors.', 'World Cup brand activations are expanding across Canada as Lay''s introduces tournament-inspired flavors. These sponsorship and retail signals help show which host markets are ramping up fan engagement before kickoff.', 'Lay''s introduces World Cup-inspired flavors in Canada', 'Tournament marketing is accelerating in Canada with new FIFA World Cup themed snack flavors.') on conflict (article_id, language_code) do nothing;

insert into public.articles (id, type, status, category, image_url, source_url, published_at) values ('b17d579a-9bf6-43b2-8235-4e02d5f9ed2a', 'news', 'published', 'Fan Experience', 'https://media.khou.com/assets/KHOU/images/b17b757d-53e4-4fcd-8b65-69ad8d492722/20260312T161923/b17b757d-53e4-4fcd-8b65-69ad8d492722_1080x1920.jpg', 'https://www.khou.com/article/money/business/houston-business-journal/fifa-world-cup-houston-legends-loft-fan-festival/285-8c399bab-79f1-45ba-8515-6c351130cdb4', '2026-03-12T21:00:00+00:00') on conflict (id) do nothing;
insert into public.article_translations (article_id, language_code, slug, title, excerpt, body, seo_title, seo_description) values ('b17d579a-9bf6-43b2-8235-4e02d5f9ed2a', 'en', 'houston-premium-world-cup-fan-experience', 'Houston adds a premium fan experience for World Cup visitors', 'Houston''s tournament preparations include new hospitality and fan-experience offerings.', 'Houston is adding premium fan-experience inventory around the 2026 World Cup, another sign that host cities are building layered offerings for visitors beyond match tickets. CupMate can surface these updates alongside stadium routes and city recommendations.', 'Houston adds a premium fan experience for World Cup visitors', 'Houston''s tournament preparations include new hospitality and fan-experience offerings.') on conflict (article_id, language_code) do nothing;
